from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

try:
    from .publisher import DEFAULT_DB_PATH
except ImportError:
    from publisher import DEFAULT_DB_PATH


QUESTION_SET_COLUMNS = [
    "set_id",
    "label",
    "short_description",
    "audience_tag",
    "level",
    "visibility",
    "required_plan",
    "is_active",
    "source_dataset_key",
    "published_at",
    "updated_at",
]

PUBLISHED_QUESTION_COLUMNS = [
    "question_id",
    "level",
    "category",
    "subtopic",
    "prompt",
    "options_json",
    "answer_index",
    "explanation",
    "option_explanations_json",
    "memory_tip",
    "is_free",
    "required_plan",
    "status",
    "source_snapshot_json",
    "editorial_source_id",
    "content_hash",
    "approved_by",
    "approved_on",
    "published_at",
    "updated_at",
]

QUESTION_SET_ITEM_COLUMNS = [
    "set_id",
    "question_id",
    "sort_order",
]


def sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def build_insert_sql(table_name: str, columns: list[str], rows: list[sqlite3.Row]) -> list[str]:
    statements: list[str] = []
    column_sql = ", ".join(columns)
    for row in rows:
        values_sql = ", ".join(sql_literal(row[column]) for column in columns)
        statements.append(f"INSERT OR REPLACE INTO {table_name} ({column_sql}) VALUES ({values_sql});")
    return statements


def export_sets(db_path: Path, set_ids: list[str], output_path: Path) -> None:
    if not set_ids:
        raise ValueError("at least one --set-id is required")

    with sqlite3.connect(db_path) as connection:
        connection.row_factory = sqlite3.Row
        placeholders = ", ".join("?" for _ in set_ids)

        question_sets = connection.execute(
            f"""
            SELECT {", ".join(QUESTION_SET_COLUMNS)}
            FROM question_sets
            WHERE set_id IN ({placeholders})
            ORDER BY set_id
            """,
            set_ids,
        ).fetchall()
        if not question_sets:
            raise LookupError("No matching question_sets found.")

        question_set_items = connection.execute(
            f"""
            SELECT {", ".join(QUESTION_SET_ITEM_COLUMNS)}
            FROM question_set_items
            WHERE set_id IN ({placeholders})
            ORDER BY set_id, sort_order
            """,
            set_ids,
        ).fetchall()

        question_ids = [str(row["question_id"]) for row in question_set_items]
        published_questions: list[sqlite3.Row] = []
        if question_ids:
            question_placeholders = ", ".join("?" for _ in question_ids)
            published_questions = connection.execute(
                f"""
                SELECT {", ".join(PUBLISHED_QUESTION_COLUMNS)}
                FROM published_questions
                WHERE question_id IN ({question_placeholders})
                ORDER BY question_id
                """,
                question_ids,
            ).fetchall()

    sql_lines: list[str] = ["-- Generated by content_admin/export_sets_to_d1_sql.py"]

    delete_placeholders = ", ".join(sql_literal(set_id) for set_id in set_ids)
    sql_lines.extend(
        [
            f"DELETE FROM question_set_items WHERE set_id IN ({delete_placeholders});",
            f"DELETE FROM publish_batches WHERE set_id IN ({delete_placeholders});",
            f"DELETE FROM question_sets WHERE set_id IN ({delete_placeholders});",
        ]
    )

    sql_lines.extend(build_insert_sql("published_questions", PUBLISHED_QUESTION_COLUMNS, published_questions))
    sql_lines.extend(build_insert_sql("question_sets", QUESTION_SET_COLUMNS, question_sets))
    sql_lines.extend(build_insert_sql("question_set_items", QUESTION_SET_ITEM_COLUMNS, question_set_items))
    sql_lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(sql_lines), encoding="utf-8")

    summary = {
        "question_sets": len(question_sets),
        "published_questions": len(published_questions),
        "question_set_items": len(question_set_items),
        "set_ids": set_ids,
        "output": str(output_path),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Export selected question sets into D1-compatible SQL.")
    parser.add_argument("--db-path", type=Path, default=DEFAULT_DB_PATH)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--set-id", dest="set_ids", action="append", required=True)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    export_sets(args.db_path, args.set_ids, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
